# Generated by Django 4.0.6 on 2022-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='display_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Display name'),
        ),
    ]
